apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: reservas-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservas-backend
  template:
    metadata:
      labels:
        app: reservas-backend
    spec:
      containers:
      - name: backend
        image: reservas-backend:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: DB_HOST
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "reservas_db"
        - name: FLASK_ENV
          value: "production"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
