apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: cGFzc3dvcmQ=  # "password" en base64
  username: cmVzZXJ2YXNfdXNlcg==  # "reservas_user" en base64
  password: cmVzZXJ2YXNfcGFzc3dvcmQ=  # "reservas_password" en base64
