apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  labels:
    app: reservas-notifications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reservas-notifications
  template:
    metadata:
      labels:
        app: reservas-notifications
    spec:
      containers:
      - name: notifications
        image: reservas-notifications:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SMTP_SERVER
          valueFrom:
            configMapKeyRef:
              name: notifications-config
              key: smtp_server
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: notifications-config
              key: smtp_port
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: notifications-secrets
              key: smtp_user
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notifications-secrets
              key: smtp_password
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              name: notifications-secrets
              key: twilio_account_sid
        - name: TWILIO_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: notifications-secrets
              key: twilio_auth_token
        - name: TWILIO_PHONE_NUMBER
          valueFrom:
            secretKeyRef:
              name: notifications-secrets
              key: twilio_phone_number
        - name: BACKEND_URL
          value: "http://backend:5000"
        - name: FLASK_ENV
          value: "production"
        ports:
        - containerPort: 5001
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/notifications/health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/notifications/health
            port: 5001
          initialDelaySeconds: 5
          periodSeconds: 5 